CREATE TABLE CUSTOMERS (
    ID SERIAL PRIMARY KEY,
    CUSTOMERNAME VARCHAR(100),
	TCNUMBER VARCHAR(11),
	GENDER VARCHAR(1),
	EMAIL VARCHAR(100),
	BIRTHDATE DATE,
	CITYID INT,
	DISTRICTID INT,
	TELNR1 VARCHAR(15),
	TELNR2 VARCHAR(15)
);

SELECT * FROM CUSTOMERS

CREATE TABLE CITIES(
ID SERIAL PRIMARY KEY,
CITY VARCHAR(50)
);

SELECT * FROM CITIES

CREATE TABLE DISTRICT(
	ID SERIAL PRIMARY KEY,
	CITYID INT,
	DISTRICT VARCHAR(50)
);

SELECT * FROM DISTRICT

DROP TABLE DISTRICT
DROP TABLE CITIES
DROP TABLE CUSTOMERS
DROP DATABASE CUSTOMERS;
